#!/usr/bin/env python3
"""Generate C++23 relation tags from the accepted relation registry."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml


ROOT = pathlib.Path(__file__).resolve().parents[2]


def parse_type(value: str) -> tuple[str, str, bool]:
    optional = value.startswith("optional<") and value.endswith(">")
    if optional:
        value = value[len("optional<") : -1]
    parameter = ""
    match = re.fullmatch(r"([a-z0-9_]+)<(.+)>", value)
    if match:
        value, parameter = match.groups()
    kinds = {
        "bool": "boolean",
        "int64": "signed_integer",
        "uint64": "unsigned_integer",
        "utf8_string": "utf8_string",
        "bytes": "bytes",
        "digest": "digest",
        "semantic_version": "semantic_version",
        "typed_id": "typed_id",
        "open_symbol": "open_symbol",
        "condition_ref": "condition_ref",
        "source_span_id": "source_span_id",
        "evidence_id": "evidence_id",
    }
    if value not in kinds:
        raise ValueError(f"unsupported generated SDK type: {value}")
    return kinds[value], parameter, optional


def string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def type_expr(value: str) -> str:
    kind, parameter, optional = parse_type(value)
    return (
        f'{{sdk::scalar_kind::{kind}, "{string(parameter)}", '
        f'{str(optional).lower()}}}'
    )


def render(relation: dict[str, object]) -> str:
    qualified = str(relation["generated_cpp_tag"])
    parts = qualified.split("::")
    if parts[0] != "cxxlens" or len(parts) < 3:
        raise ValueError(f"invalid generated_cpp_tag: {qualified}")
    namespace = "::".join(parts[:-1])
    tag = parts[-1]
    descriptor_id = str(relation["descriptor_id"])
    columns = relation["columns"]
    assert isinstance(columns, list)
    lines = [
        "#pragma once",
        "",
        "/** Generated by cxxlens relation_idl_compiler.py; do not hand edit. */",
        "#include <cxxlens/sdk/query.hpp>",
        "",
        f"namespace {namespace}",
        "{",
        f"\tstruct {tag}",
        "\t{",
        "\t\t[[nodiscard]] static const sdk::relation_descriptor& descriptor()",
        "\t\t{",
        "\t\t\tstatic const sdk::relation_descriptor value = []",
        "\t\t\t{",
        "\t\t\t\tsdk::relation_descriptor output;",
        f'\t\t\t\toutput.id = "{string(descriptor_id)}";',
        f'\t\t\t\toutput.name = "{string(str(relation["name"]))}";',
    ]
    version = [int(part) for part in str(relation["version"]).split(".")]
    lines.extend(
        [
            f"\t\t\t\toutput.version = {{{version[0]}U, {version[1]}U, {version[2]}U}};",
            f'\t\t\t\toutput.semantic_major = {int(relation["semantic_major"])}U;',
            "\t\t\t\toutput.columns = {",
        ]
    )
    for column in columns:
        assert isinstance(column, dict)
        required = bool(column.get("required", False))
        lines.append(
            f'\t\t\t\t\t{{"{string(str(column["id"]))}", '
            f'"{string(str(column["name"]))}", {type_expr(str(column["type"]))}, '
            f'{str(required).lower()}}},'
        )
    lines.extend(
        [
            "\t\t\t\t};",
            "\t\t\t\toutput.descriptor_digest =",
            "\t\t\t\t\tsdk::semantic_digest(\"cxxlens.relation-descriptor.v1\", output.canonical_form());",
            "\t\t\t\treturn output;",
            "\t\t\t}();",
            "\t\t\treturn value;",
            "\t\t}",
        ]
    )
    for column in columns:
        assert isinstance(column, dict)
        lines.extend(
            [
                f'\t\tstruct {column["name"]}',
                "\t\t{",
                "\t\t\t[[nodiscard]] static sdk::column_ref ref()",
                "\t\t\t{",
                f'\t\t\t\treturn {{{tag}::descriptor().id, "{string(str(column["id"]))}", '
                f'{type_expr(str(column["type"]))}}};',
                "\t\t\t}",
                "\t\t};",
            ]
        )
    lines.extend(["\t};", f"}} // namespace {namespace}", ""])
    return "\n".join(lines)


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--registry",
        type=pathlib.Path,
        default=ROOT / "schemas/cxxlens_ng_relation_registry.yaml",
    )
    parser.add_argument("--relation", required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = arguments()
    document = yaml.safe_load(args.registry.read_text(encoding="utf-8"))
    relation = next(
        (item for item in document["relations"] if item["name"] == args.relation),
        None,
    )
    if relation is None:
        print(f"relation not found: {args.relation}", file=sys.stderr)
        return 2
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(relation), encoding="utf-8")
    print(f"generated {args.relation} -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
