#!/usr/bin/env python3
"""Generate C++23 relation tags from the accepted relation registry."""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

import jsonschema
import yaml


ROOT = pathlib.Path(__file__).resolve().parents[2]


def parse_type(value: str) -> tuple[str, str, bool]:
    optional = value.startswith("optional<") and value.endswith(">")
    if optional:
        value = value[len("optional<") : -1]
    parameter = ""
    match = re.fullmatch(r"([a-z0-9_]+)<(.+)>", value)
    if match:
        value, parameter = match.groups()
    kinds = {
        "bool": "boolean",
        "int64": "signed_integer",
        "uint64": "unsigned_integer",
        "utf8_string": "utf8_string",
        "bytes": "bytes",
        "digest": "digest",
        "semantic_version": "semantic_version",
        "typed_id": "typed_id",
        "open_symbol": "open_symbol",
        "condition_ref": "condition_ref",
        "source_span_id": "source_span_id",
        "evidence_id": "evidence_id",
        "closed_symbol": "closed_symbol",
        "set": "set",
    }
    if value not in kinds:
        raise ValueError(f"unsupported generated SDK type: {value}")
    return kinds[value], parameter, optional


def string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def type_expr(value: str) -> str:
    kind, parameter, optional = parse_type(value)
    return (
        f'{{sdk::scalar_kind::{kind}, "{string(parameter)}", '
        f'{str(optional).lower()}}}'
    )


def render(relation: dict[str, object]) -> str:
    qualified = str(relation["generated_cpp_tag"])
    parts = qualified.split("::")
    if parts[0] != "cxxlens" or len(parts) < 3:
        raise ValueError(f"invalid generated_cpp_tag: {qualified}")
    namespace = "::".join(parts[:-1])
    tag = parts[-1]
    descriptor_id = str(relation["descriptor_id"])
    generated_filename = str(relation["name"]).replace(".", "_") + ".hpp"
    contract_canonical = json.dumps(
        relation, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    )
    contract_digest = "sha256:" + hashlib.sha256(
        contract_canonical.encode("utf-8")
    ).hexdigest()
    columns = relation["columns"]
    assert isinstance(columns, list)
    lines = [
        "#pragma once",
        "",
        "/**",
        f" * @file {generated_filename}",
        " * @brief Generated by cxxlens relation_idl_compiler.py; do not hand edit.",
        " */",
        "#include <cxxlens/sdk/query.hpp>",
        "",
        "// clang-format off",
        f"namespace {namespace}",
        "{",
        f'\t/** @brief Generated relation tag backed by descriptor `{descriptor_id}`. */',
        f"\tstruct {tag}",
        "\t{",
        "\t\t/** @brief Return the immutable descriptor shared with dynamic lookup. */",
        "\t\t[[nodiscard]] static const sdk::relation_descriptor& descriptor()",
        "\t\t{",
        "\t\t\tstatic const sdk::relation_descriptor value = []",
        "\t\t\t{",
        "\t\t\t\tsdk::relation_descriptor output;",
        f'\t\t\t\toutput.id = "{string(descriptor_id)}";',
        f'\t\t\t\toutput.name = "{string(str(relation["name"]))}";',
    ]
    version = [int(part) for part in str(relation["version"]).split(".")]
    lines.extend(
        [
            f"\t\t\t\toutput.version = {{{version[0]}U, {version[1]}U, {version[2]}U}};",
            f'\t\t\t\toutput.semantic_major = {int(relation["semantic_major"])}U;',
            f'\t\t\t\toutput.semantics = "{string(str(relation["semantics"]))}";',
            f'\t\t\t\toutput.owner_namespace = "{string(str(relation["owner_namespace"]))}";',
            f'\t\t\t\toutput.contract_canonical = R"cxxlens({contract_canonical})cxxlens";',
            f'\t\t\t\toutput.contract_digest = "{contract_digest}";',
            "\t\t\t\toutput.columns = {",
        ]
    )
    for column in columns:
        assert isinstance(column, dict)
        required = bool(column.get("required", False))
        role = str(column.get("identity_role", "auxiliary"))
        lines.append(
            f'\t\t\t\t\t{{"{string(str(column["id"]))}", '
            f'"{string(str(column["name"]))}", {type_expr(str(column["type"]))}, '
            f'{str(required).lower()}, sdk::column_role::{role}}},'
        )
    claim = relation["claim"]
    assert isinstance(claim, dict)
    key = claim["key"]
    assert isinstance(key, list)
    references = relation.get("references", [])
    assert isinstance(references, list)
    merge = relation["merge"]
    assert isinstance(merge, dict)
    lines.extend(
        [
            "\t\t\t\t};",
            "\t\t\t\toutput.key_columns = {",
            *[f'\t\t\t\t\t"{string(str(value))}",' for value in key],
            "\t\t\t\t};",
            "\t\t\t\toutput.references = {",
        ]
    )
    for reference in references:
        assert isinstance(reference, dict)
        source = ", ".join(f'"{string(str(value))}"' for value in reference["source_columns"])
        target = ", ".join(f'"{string(str(value))}"' for value in reference["target_columns"])
        lines.append(
            f'\t\t\t\t\t{{{{{source}}}, "{string(str(reference["target_relation"]))}", '
            f'{{{target}}}, sdk::reference_strength::{reference["strength"]}}},'
        )
    conflict_columns = merge.get("conflict_columns", [])
    assert isinstance(conflict_columns, list)
    lines.extend(
        [
            "\t\t\t\t};",
            f'\t\t\t\toutput.merge = sdk::merge_mode::{merge["mode"]};',
            "\t\t\t\toutput.conflict_columns = {",
            *[f'\t\t\t\t\t"{string(str(value))}",' for value in conflict_columns],
            "\t\t\t\t};",
            "\t\t\t\toutput.descriptor_digest = *sdk::semantic_digest(",
            '\t\t\t\t\t"cxxlens.relation-descriptor-binding.v2",',
            "\t\t\t\t\toutput.contract_digest + \"\\n\" + output.canonical_form());",
            "\t\t\t\treturn output;",
            "\t\t\t}();",
            "\t\t\treturn value;",
            "\t\t}",
            f"\t\tusing builder = sdk::static_row_builder<{tag}>;",
            f"\t\tusing view = sdk::static_row_view<{tag}>;",
        ]
    )
    for column in columns:
        assert isinstance(column, dict)
        column_tag = str(column["name"])
        if column_tag == tag:
            column_tag += "_column"
        lines.extend(
            [
                f'\t\t/** @brief Generated column tag for `{column["id"]}`. */',
                f"\t\tstruct {column_tag}",
                "\t\t{",
                "\t\t\t/** @brief Materialize the stable descriptor/column/type reference. */",
                "\t\t\t[[nodiscard]] static sdk::column_ref ref()",
                "\t\t\t{",
                f'\t\t\t\treturn {{{tag}::descriptor().id, "{string(str(column["id"]))}", '
                f'{type_expr(str(column["type"]))}}};',
                "\t\t\t}",
                "\t\t};",
            ]
        )
    lines.extend(["\t};", f"}} // namespace {namespace}", "// clang-format on", ""])
    return "\n".join(lines)


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--registry",
        type=pathlib.Path,
        default=ROOT / "schemas/cxxlens_ng_relation_registry.yaml",
    )
    parser.add_argument("--relation", required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = arguments()
    document = yaml.safe_load(args.registry.read_text(encoding="utf-8"))
    schema = yaml.safe_load(
        (ROOT / "schemas/cxxlens_ng_relation_registry.schema.yaml").read_text(
            encoding="utf-8"
        )
    )
    try:
        jsonschema.Draft202012Validator(schema).validate(document)
    except jsonschema.ValidationError as error:
        print(f"relation registry validation failed: {error.message}", file=sys.stderr)
        return 2
    names = [str(item["name"]) for item in document["relations"]]
    tags = [str(item["generated_cpp_tag"]) for item in document["relations"]]
    if len(names) != len(set(names)) or len(tags) != len(set(tags)):
        print("relation registry contains duplicate names or C++ tags", file=sys.stderr)
        return 2
    relation = next(
        (item for item in document["relations"] if item["name"] == args.relation),
        None,
    )
    if relation is None:
        print(f"relation not found: {args.relation}", file=sys.stderr)
        return 2
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(relation), encoding="utf-8")
    print(f"generated {args.relation} -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
