#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one exact match, found {count}")
    return text.replace(old, new, 1)


def replace_regex(text: str, pattern: str, replacement: str, label: str) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.DOTALL)
    if count != 1:
        raise RuntimeError(f"{label}: expected one regex match, found {count}")
    return updated


source_path = Path("src/runtime/provider_process_adapter.cpp")
source = source_path.read_text(encoding="utf-8")
source = replace_once(
    source,
    "#include <poll.h>\n#include <sys/mman.h>",
    "#include <poll.h>\n#include <pthread.h>\n#include <sys/mman.h>",
    "pthread include",
)

class_marker = "\n\t\t/**\n\t\t * Live Linux process channel used by the source-private NG1 seam."
sigpipe_helper = r'''

		/**
		 * A pipe write reports EPIPE and generates SIGPIPE in the calling thread.  A library
		 * transport must not change the process-wide signal disposition, so block SIGPIPE only
		 * around this write and consume the signal generated by this call before restoring the
		 * caller's mask.  A SIGPIPE that was already pending remains pending.
		 */
		[[nodiscard]] ssize_t write_without_sigpipe(const int destination,
												 const void* const data,
												 const std::size_t size) noexcept
		{
			sigset_t blocked{};
			sigset_t previous{};
			if (::sigemptyset(&blocked) != 0 || ::sigaddset(&blocked, SIGPIPE) != 0)
				return -1;
			const auto block_error = ::pthread_sigmask(SIG_BLOCK, &blocked, &previous);
			if (block_error != 0)
			{
				errno = block_error;
				return -1;
			}

			sigset_t pending{};
			if (::sigpending(&pending) != 0)
			{
				const auto pending_error = errno;
				(void)::pthread_sigmask(SIG_SETMASK, &previous, nullptr);
				errno = pending_error;
				return -1;
			}
			const bool already_pending = ::sigismember(&pending, SIGPIPE) == 1;
			const auto written = ::write(destination, data, size);
			const auto write_error = written < 0 ? errno : 0;
			if (written < 0 && write_error == EPIPE && !already_pending)
			{
				timespec immediate{};
				while (::sigtimedwait(&blocked, nullptr, &immediate) < 0 && errno == EINTR)
				{
				}
			}
			const auto restore_error = ::pthread_sigmask(SIG_SETMASK, &previous, nullptr);
			if (restore_error != 0)
			{
				errno = restore_error;
				return -1;
			}
			if (written < 0)
				errno = write_error;
			return written;
		}
'''
source = replace_once(source, class_marker, sigpipe_helper + class_marker, "SIGPIPE helper")

new_send_frame = r'''			result<void> send_frame(const frame& value) override
			{
				if (finished_ || input_.get() < 0)
					return cxxlens::sdk::unexpected(process_error(
						"provider.protocol-state-invalid", "ng1-live", "input-closed"));
				if (auto deadline = check_deadline(); !deadline)
					return deadline;
				auto encoded = encode_frame(value, limits_);
				if (!encoded)
					return cxxlens::sdk::unexpected(std::move(encoded.error()));

				std::size_t offset{};
				while (offset < encoded->size())
				{
					const auto written = write_without_sigpipe(
						input_.get(), encoded->data() + offset, encoded->size() - offset);
					if (written > 0)
					{
						offset += static_cast<std::size_t>(written);
						continue;
					}
					if (written < 0 && errno == EPIPE)
						return cxxlens::sdk::unexpected(process_error(
							"provider.worker-exit", "ng1-live-write", "stdin-closed"));
					if (written < 0 && errno == EINTR)
						continue;
					if (written < 0 && (errno == EAGAIN || errno == EWOULDBLOCK))
					{
						std::array<pollfd, 3U> descriptors{
							pollfd{input_.get(), POLLOUT | POLLHUP | POLLERR, 0},
							pollfd{stdout_ended_ ? -1 : output_.get(),
								   POLLIN | POLLHUP | POLLERR,
								   0},
							pollfd{stderr_ended_ ? -1 : error_.get(),
								   POLLIN | POLLHUP | POLLERR,
								   0},
						};
						const auto polled = ::poll(descriptors.data(), descriptors.size(), 10);
						if (polled < 0 && errno == EINTR)
							continue;
						if (polled < 0)
							return cxxlens::sdk::unexpected(
								process_error("provider.process-launch-failed",
											  "ng1-live-write",
											  std::to_string(errno)));
						if (!drain_stdout() || !drain_stderr())
						{
							(void)terminate(process_status::output_limit);
							return cxxlens::sdk::unexpected(process_error(
								"provider.output-limit", "ng1-live", "transport-bytes"));
						}
						if ((descriptors[0].revents & (POLLHUP | POLLERR | POLLNVAL)) != 0)
							return cxxlens::sdk::unexpected(process_error(
								"provider.worker-exit", "ng1-live-write", "stdin-closed"));
						if (auto deadline = check_deadline(); !deadline)
							return deadline;
						continue;
					}
					return cxxlens::sdk::unexpected(process_error(
						"provider.process-launch-failed", "ng1-live-write", std::to_string(errno)));
				}
				return {};
			}
'''
source = replace_regex(
    source,
    r"\t\t\tresult<void> send_frame\(const frame& value\) override\n\t\t\t\{.*?\n\t\t\t\}(?=\n\n\t\t\tresult<std::optional<frame>> receive_frame)",
    new_send_frame,
    "send_frame",
)

new_finish = r'''			result<process_output> finish(const std::stop_token cancellation) override
			{
				if (finished_)
					return cxxlens::sdk::unexpected(
						process_error("provider.protocol-state-invalid", "ng1-live", "finished"));
				input_.reset();
				for (;;)
				{
					reap_nonblocking();
					if (cancellation.stop_requested())
					{
						forced_status_ = process_status::cancelled;
						kill_process_group();
					}
					if (reaped_ && stdout_ended_ && stderr_ended_)
						break;
					if (std::chrono::steady_clock::now() >= deadline_)
					{
						forced_status_ = process_status::timed_out;
						kill_process_group();
						output_.reset();
						error_.reset();
						stdout_ended_ = true;
						stderr_ended_ = true;
						break;
					}
					std::array<pollfd, 2U> descriptors{
						pollfd{output_.get(), POLLIN | POLLHUP | POLLERR, 0},
						pollfd{error_.get(), POLLIN | POLLHUP | POLLERR, 0},
					};
					const auto polled = ::poll(descriptors.data(), descriptors.size(), 10);
					if (polled < 0 && errno == EINTR)
						continue;
					if (polled < 0)
						return cxxlens::sdk::unexpected(
							process_error("provider.process-launch-failed",
										  "ng1-live-finish",
										  std::to_string(errno)));
					if (!drain_stdout() || !drain_stderr())
					{
						forced_status_ = process_status::output_limit;
						kill_process_group();
					}
				}
				finished_ = true;
				process_output output;
				output.status = forced_status_;
				if (forced_status_ == process_status::launch_failed)
				{
					if (WIFSIGNALED(wait_status_))
					{
						output.status = process_status::crashed;
						output.termination_signal = WTERMSIG(wait_status_);
					}
					else if (WIFEXITED(wait_status_))
					{
						output.status = process_status::exited;
						output.exit_code = WEXITSTATUS(wait_status_);
					}
				}
				else if (WIFSIGNALED(wait_status_))
					output.termination_signal = WTERMSIG(wait_status_);
				else if (WIFEXITED(wait_status_))
					output.exit_code = WEXITSTATUS(wait_status_);
				output.standard_output = std::move(stdout_bytes_);
				output.standard_error = std::move(stderr_text_);
				output.measured_executable_digest = measured_digest_;
				output.sandbox = sandbox_evidence(
					policy_, budget_, sandbox_assurance::enforced, true, measured_digest_);
				if (output.exit_code == 126 && output.status == process_status::exited)
				{
					output.failure_code = "security.sandbox-insufficient";
					output.sandbox = sandbox_evidence(
						policy_, budget_, sandbox_assurance::none, false, measured_digest_);
				}
				return output;
			}
'''
source = replace_regex(
    source,
    r"\t\t\tresult<process_output> finish\(const std::stop_token cancellation\) override\n\t\t\t\{.*?\n\t\t\t\}(?=\n\n\t\t\tresult<process_output> terminate)",
    new_finish,
    "finish",
)

new_reap_and_kill = r'''			void reap_nonblocking() noexcept
			{
				// Keep the group leader waitable while a descendant may still retain an output pipe.
				// This preserves a stable process-group identity for timeout and cancellation cleanup.
				if (reaped_ || child_ <= 0 || !stdout_ended_ || !stderr_ended_)
					return;
				const auto waited = ::waitpid(child_, &wait_status_, WNOHANG);
				if (waited == child_ || (waited < 0 && errno == ECHILD))
					reaped_ = true;
			}

			void kill_process_group() noexcept
			{
				if (child_ <= 0)
					return;
				const auto signal_deadline =
					std::chrono::steady_clock::now() + std::chrono::milliseconds{100};
				for (;;)
				{
					if (::kill(-child_, SIGKILL) != 0 && errno == ESRCH)
						break;
					if (std::chrono::steady_clock::now() >= signal_deadline)
						break;
					std::this_thread::sleep_for(std::chrono::milliseconds{1});
				}
				if (!reaped_)
				{
					for (;;)
					{
						const auto waited = ::waitpid(child_, &wait_status_, 0);
						if (waited == child_ || (waited < 0 && errno == ECHILD))
						{
							reaped_ = true;
							break;
						}
						if (waited < 0 && errno == EINTR)
							continue;
						break;
					}
				}
			}
'''
source = replace_regex(
    source,
    r"\t\t\tvoid reap_nonblocking\(\) noexcept\n\t\t\t\{.*?\n\t\t\t\}\n\n\t\t\tvoid kill_process_group\(\) noexcept\n\t\t\t\{.*?\n\t\t\t\}(?=\n\n\t\t\tdescriptor input_)",
    new_reap_and_kill,
    "reap and kill",
)
source_path.write_text(source, encoding="utf-8")

fixture_path = Path("tests/fixtures/provider_process_fixture.cpp")
fixture = fixture_path.read_text(encoding="utf-8")
fixture_marker = "\n\tstd::vector<std::byte> input;\n"
fixture_mode = r'''
#if defined(__linux__) && defined(__GLIBC__)
	if (mode == "ng1-stderr-before-input")
	{
		constexpr std::size_t total_output = 2U * 1024U * 1024U;
		std::array<char, 4096U> output_chunk{};
		output_chunk.fill('x');
		std::size_t emitted{};
		while (emitted < total_output)
		{
			const auto requested = std::min(output_chunk.size(), total_output - emitted);
			const auto written = ::write(STDERR_FILENO, output_chunk.data(), requested);
			if (written > 0)
			{
				emitted += static_cast<std::size_t>(written);
				continue;
			}
			if (written < 0 && errno == EINTR)
				continue;
			return static_cast<int>(exit_code::read_failure);
		}

		std::array<std::byte, 65536U> input_chunk{};
		for (;;)
		{
			const auto count = ::read(STDIN_FILENO, input_chunk.data(), input_chunk.size());
			if (count > 0)
				continue;
			if (count == 0)
				return EXIT_SUCCESS;
			if (errno == EINTR)
				continue;
			return static_cast<int>(exit_code::read_failure);
		}
	}
#endif
'''
fixture = replace_once(fixture, fixture_marker, fixture_mode + fixture_marker, "fixture mode")
fixture_path.write_text(fixture, encoding="utf-8")

test_path = Path("tests/unit/sdk/provider_runtime_test.cpp")
test = test_path.read_text(encoding="utf-8")
new_test_function = r'''	void check_ng1_live_duplex_process(const std::string& executable)
	{
#if defined(__linux__) && defined(__GLIBC__)
		const auto policy = baseline_policy();
		auto make_system_invocation = [&](const std::string& path,
											  const std::uint64_t wall_ms,
											  const std::uint64_t transport_bytes)
		{
			process_invocation value;
			value.argv = {path};
			value.budget.wall_ms = wall_ms;
			value.budget.cpu_ms = wall_ms;
			value.budget.address_space_bytes = provider_address_space_budget;
			value.budget.transport_bytes = transport_bytes;
			value.budget.output_bytes = transport_bytes;
			value.budget.open_files = 64U;
			value.budget.subprocesses = provider_subprocess_budget;
			value.sandbox = {sandbox_assurance::enforced, policy.policy_digest()};
			value.expected_binary_digest = executable_digest(path);
			return value;
		};

		protocol_limits limits;
		limits.minimum_minor = 1U;
		limits.maximum_minor = 1U;
		auto port = detail::make_system_ng1_duplex_process_port();
		require(port != nullptr, "NG1 live process port was not created");

		auto staged_digest = semantic_digest("test.ng1.live", "staged");
		require(staged_digest.has_value(), "NG1 live staged digest construction failed");
		detail::ng1_heartbeat_control control{"cxxlens.provider-control.heartbeat.v1",
											  detail::ng1_heartbeat_kind::ack,
											  "provider:test",
											  {1U, 2U, 3U},
											  "session:test",
											  "task:test",
											  7U,
											  0U,
											  123U,
											  0U,
											  *staged_digest};
		auto encoded_control = detail::encode_ng1_heartbeat_control(control);
		require(encoded_control.has_value(), "NG1 live heartbeat encoding failed");
		frame wire;
		wire.type = detail::ng1_heartbeat_message_type;
		wire.stream_id = 7U;
		wire.sequence = 0U;
		wire.control = *encoded_control;
		wire.protocol_major = 1U;
		wire.protocol_minor = 1U;

		auto invocation = make_system_invocation("/bin/cat", 3000U, 1024U * 1024U);
		auto process = port->start(invocation, limits, {});
		if (!process)
			require(false, "NG1 live process launch failed: " + process.error().code);
		auto sent = (*process)->send_frame(wire);
		require(sent.has_value(), "NG1 live frame send failed");
		auto received = (*process)->receive_frame({});
		require(received.has_value() && received->has_value(),
				"NG1 live frame receive reached EOF");
		require(received->value().type == wire.type &&
					received->value().stream_id == wire.stream_id &&
					received->value().sequence == wire.sequence &&
					received->value().control == wire.control &&
					received->value().payload == wire.payload &&
					received->value().protocol_major == wire.protocol_major &&
					received->value().protocol_minor == wire.protocol_minor &&
					received->value().flags == wire.flags,
				"NG1 live frame round trip changed wire data");
		auto finished = (*process)->finish({});
		require(finished.has_value() && finished->status == process_status::exited &&
					finished->exit_code == 0 &&
					finished->measured_executable_digest == invocation.expected_binary_digest,
				"NG1 live process did not finish with exact identity and exit evidence");
		require(finished->sandbox.achieved == sandbox_assurance::enforced,
				"NG1 live process lost enforced sandbox evidence");

		auto rejected_process = port->start(invocation, limits, {});
		if (!rejected_process)
			require(false,
					"NG1 live negative process launch failed: " + rejected_process.error().code);
		auto optional_wire = wire;
		optional_wire.flags = static_cast<std::uint16_t>(frame_flag::optional_extension);
		auto rejected = (*rejected_process)->send_frame(optional_wire);
		require(!rejected && rejected.error().code == "provider.protocol-state-invalid",
				"NG1 live channel accepted optional flags on the reserved heartbeat");
		auto terminated = (*rejected_process)->terminate(process_status::cancelled);
		require(terminated.has_value() && terminated->status == process_status::cancelled,
				"NG1 live channel did not preserve explicit cancellation evidence");

		auto input_budget_invocation = baseline_invocation(
			executable, "deadlock", executable_digest(executable), 2000U, 1U);
		auto input_budget_process = port->start(input_budget_invocation, limits, {});
		if (!input_budget_process)
			require(false,
					"NG1 host-input budget fixture launch failed: " +
						input_budget_process.error().code);
		auto input_budget_sent = (*input_budget_process)->send_frame(wire);
		require(input_budget_sent.has_value(),
				"NG1 host frame was incorrectly charged to the output transport budget");
		auto input_budget_terminated =
			(*input_budget_process)->terminate(process_status::cancelled);
		require(input_budget_terminated.has_value() &&
					input_budget_terminated->status == process_status::cancelled,
				"NG1 host-input budget fixture did not terminate cleanly");

		auto closed_input_invocation =
			make_system_invocation("/bin/true", 2000U, 1024U * 1024U);
		auto closed_input_process = port->start(closed_input_invocation, limits, {});
		if (!closed_input_process)
			require(false,
					"NG1 closed-input fixture launch failed: " + closed_input_process.error().code);
		std::this_thread::sleep_for(std::chrono::milliseconds{100});
		auto closed_input_sent = (*closed_input_process)->send_frame(wire);
		require(!closed_input_sent && closed_input_sent.error().code == "provider.worker-exit",
				"NG1 closed provider stdin did not return the typed worker-exit failure");
		auto closed_input_finished = (*closed_input_process)->finish({});
		require(closed_input_finished.has_value() &&
					closed_input_finished->status == process_status::exited,
				"NG1 closed-input fixture did not remain host-process safe");

		constexpr std::size_t duplex_bytes = 2U * 1024U * 1024U;
		auto duplex_invocation = baseline_invocation(executable,
													"ng1-stderr-before-input",
													executable_digest(executable),
													3000U,
													4U * 1024U * 1024U);
		auto duplex_process = port->start(duplex_invocation, limits, {});
		if (!duplex_process)
			require(false, "NG1 duplex fixture launch failed: " + duplex_process.error().code);
		frame large_input;
		large_input.type = message_type::input_chunk;
		large_input.stream_id = 8U;
		large_input.sequence = 0U;
		large_input.payload.assign(duplex_bytes, std::byte{0x5a});
		large_input.protocol_major = 1U;
		large_input.protocol_minor = 1U;
		auto duplex_sent = (*duplex_process)->send_frame(large_input);
		require(duplex_sent.has_value(),
				"NG1 duplex channel deadlocked instead of draining provider output");
		auto duplex_finished = (*duplex_process)->finish({});
		require(duplex_finished.has_value() &&
					duplex_finished->status == process_status::exited &&
					duplex_finished->exit_code == 0 &&
					duplex_finished->standard_error.size() == duplex_bytes,
				"NG1 duplex fixture did not preserve bounded stderr while accepting input");

		const auto marker = make_marker_path("ng1-descendant-holder");
		const auto sentinel = std::filesystem::path{marker.string() + ".sentinel"};
		std::error_code ignored;
		std::filesystem::remove(marker, ignored);
		std::filesystem::remove(sentinel, ignored);
		auto descendant_invocation = baseline_invocation(executable,
													"deadlock-descendant-holder",
													executable_digest(executable),
													1000U,
													1024U * 1024U);
		descendant_invocation.environment.emplace_back("CXXLENS_FIXTURE_MARKER",
																 marker.string());
		auto descendant_process = port->start(descendant_invocation, limits, {});
		if (!descendant_process)
			require(false,
					"NG1 descendant fixture launch failed: " + descendant_process.error().code);
		auto descendant_finished = (*descendant_process)->finish({});
		const auto holder = wait_for_marker(marker);
		bool holder_exited{};
		if (holder > 0)
		{
			const auto holder_pidfd = open_pidfd(holder);
			if (holder_pidfd >= 0)
			{
				holder_exited = wait_pidfd_exit(holder_pidfd, std::chrono::milliseconds{1500});
				(void)::close(holder_pidfd);
			}
			else if (errno == ESRCH)
				holder_exited = true;
			if (!holder_exited)
				(void)::kill(holder, SIGKILL);
		}
		const bool sentinel_absent = !std::filesystem::exists(sentinel);
		std::filesystem::remove(marker, ignored);
		std::filesystem::remove(sentinel, ignored);
		require(descendant_finished.has_value() &&
					descendant_finished->status == process_status::timed_out,
				"NG1 leader exit with retained descendant pipes lost the timeout outcome");
		require(holder > 0 && holder_exited,
				"NG1 timeout left a descendant process alive after the group leader exited");
		require(sentinel_absent,
				"NG1 descendant survived long enough to perform a post-timeout side effect");
#else
		(void)executable;
		// The unavailable implementation is intentionally fail-closed on non-Linux platforms.
#endif
	}
'''
test = replace_regex(
    test,
    r"\tvoid check_ng1_live_duplex_process\(\)\n\t\{.*?\n\t\}(?=\n\n\} // namespace)",
    new_test_function,
    "NG1 live duplex test",
)
test = replace_once(
    test,
    "\tcheck_ng1_live_duplex_process();",
    "\tcheck_ng1_live_duplex_process(executable);",
    "NG1 live duplex call",
)
test_path.write_text(test, encoding="utf-8")
