#!/usr/bin/env python3
"""Tests for the generated documentation and asset migration contract."""

from __future__ import annotations

import importlib.util
import json
import pathlib
import subprocess
import tempfile
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[2]
MODULE_PATH = ROOT / "tools/quality/check_documentation_consistency.py"
SPEC = importlib.util.spec_from_file_location("documentation_consistency", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


class DocumentationConsistencyTests(unittest.TestCase):
    def test_generated_ledger_matches_repository(self) -> None:
        policy, expected = MODULE.generate_ledger(ROOT)
        actual = json.loads((ROOT / MODULE.LEDGER).read_text(encoding="utf-8"))
        self.assertEqual(expected, actual)
        self.assertEqual(actual["asset_count"], len(actual["assets"]))
        self.assertEqual(
            actual["asset_count"], len({row["path"] for row in actual["assets"]})
        )
        MODULE.validate_documentation(ROOT, policy, actual)

    def test_promoted_catalogs_are_accepted_exact_contracts(self) -> None:
        relation = MODULE.load_yaml(ROOT / MODULE.CATALOGS["relation-registry"])
        self.assertEqual(relation["maturity"], "accepted")
        self.assertEqual(relation["schema"], "cxxlens.relation-registry.v1")
        provider = MODULE.load_yaml(ROOT / MODULE.CATALOGS["provider-protocol"])
        self.assertEqual(provider["maturity"], "accepted")
        self.assertEqual(provider["schema"], "cxxlens.provider-protocol.v1")
        security = MODULE.load_yaml(ROOT / MODULE.CATALOGS["security-profile"])
        self.assertEqual(security["maturity"], "accepted")
        self.assertEqual(security["schema"], "cxxlens.security-profile.v1")
        for kind, path in MODULE.CATALOGS.items():
            if kind not in {"relation-registry", "provider-protocol", "security-profile"}:
                self.assertEqual(MODULE.load_yaml(ROOT / path)["maturity"], "bootstrap")

    def test_missing_replacement_is_rejected(self) -> None:
        record = {
            "disposition": "replace",
            "status": "planned",
            "owner": "steward.test",
            "profile": "migration",
            "authority": "implementation",
            "replacement": None,
            "removal_issue": "#72",
        }
        with self.assertRaisesRegex(MODULE.DocumentationError, "no replacement"):
            MODULE.validate_record("src/example.cpp", record)

    def test_archive_without_front_matter_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "legacy.md"
            path.write_text("# Legacy\n", encoding="utf-8")
            with self.assertRaisesRegex(MODULE.DocumentationError, "front matter"):
                MODULE.front_matter(path)

    def test_broken_active_link_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            path = root / "README.md"
            path.write_text("# Current\n\n[missing](docs/missing.md)\n", encoding="utf-8")
            with self.assertRaisesRegex(MODULE.DocumentationError, "broken"):
                MODULE.validate_links(root, ["README.md"])

    def test_ci_created_untracked_asset_is_not_repository_owned(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            subprocess.run(["git", "init", "-q", str(root)], check=True)
            tracked = root / "tracked.txt"
            tracked.write_text("tracked\n", encoding="utf-8")
            subprocess.run(["git", "-C", str(root), "add", "tracked.txt"], check=True)
            (root / "llvm.sh").write_text("generated by CI\n", encoding="utf-8")

            self.assertEqual(
                MODULE.repository_assets(root),
                [MODULE.LEDGER.as_posix(), "tracked.txt"],
            )


if __name__ == "__main__":
    unittest.main()
