function(cxxlens_enable_sanitizers target)
  get_target_property(cxxlens_sanitizers_configured ${target}
                      CXXLENS_SANITIZERS_CONFIGURED)
  if(cxxlens_sanitizers_configured)
    return()
  endif()
  set_property(TARGET ${target} PROPERTY CXXLENS_SANITIZERS_CONFIGURED TRUE)

  if(CXXLENS_ENABLE_TSAN AND (CXXLENS_ENABLE_ASAN OR CXXLENS_ENABLE_UBSAN))
    message(FATAL_ERROR "ThreadSanitizer requires a separate build")
  endif()
  if(MSVC)
    if(CXXLENS_ENABLE_ASAN)
      target_compile_options(${target} PRIVATE /fsanitize=address)
      target_link_options(${target} PUBLIC /fsanitize=address)
    endif()
    return()
  endif()

  set(sanitizers "")
  if(CXXLENS_ENABLE_ASAN)
    list(APPEND sanitizers address)
  endif()
  if(CXXLENS_ENABLE_UBSAN)
    list(APPEND sanitizers undefined)
  endif()
  if(CXXLENS_ENABLE_TSAN)
    list(APPEND sanitizers thread)
  endif()
  if(sanitizers)
    list(JOIN sanitizers "," sanitizer_list)
    target_compile_options(${target} PRIVATE "-fsanitize=${sanitizer_list}"
                                             -fno-omit-frame-pointer)
    target_link_options(${target} PUBLIC "-fsanitize=${sanitizer_list}")
  endif()
endfunction()
