function(cxxlens_enable_consumer_sanitizers target)
  if(CXXLENS_ENABLE_TSAN AND (CXXLENS_ENABLE_ASAN OR CXXLENS_ENABLE_UBSAN))
    message(FATAL_ERROR "ThreadSanitizer requires a separate consumer build")
  endif()
  set(sanitizers "")
  if(CXXLENS_ENABLE_ASAN)
    list(APPEND sanitizers address)
  endif()
  if(CXXLENS_ENABLE_UBSAN)
    list(APPEND sanitizers undefined)
  endif()
  if(CXXLENS_ENABLE_TSAN)
    list(APPEND sanitizers thread)
  endif()
  if(sanitizers)
    list(JOIN sanitizers "," sanitizer_list)
    target_compile_options(${target} PRIVATE "-fsanitize=${sanitizer_list}"
                                             -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE "-fsanitize=${sanitizer_list}")
  endif()
endfunction()
